export const extractedQrData: Record<string, { type: 'map' | 'household', value: string }> = {
  "Sơ đồ địa giới - Thôn Lương Lễ": { type: "map", value: "https://assets.icheck.vn/image/2026/app/8/25/9de5f5b0f37a69ffcbc4c88918687809.png" },
  "Sơ đồ địa giới - Thôn 3A": { type: "map", value: "https://assets.icheck.vn/image/2026/app/8/25/1d20e283cb9f10e82c746a6042bc081c.png" },
  "Thôn Lương Lễ - xã Khe Sanh": { type: "map", value: "https://qr-i.io/image/smart-village%20/smart-village-overview.png" },
  "Thôn 3A - Xã Khe Sanh": { type: "map", value: "https://qr-i.io/image/smart-village%20/smart-village-overview.png" },
  "Xóm 5 - Thôn Lương Lễ": { type: "household", value: "Số 29" },
  "Xóm 4 - Thôn Lương Lễ": { type: "household", value: "Số 12" },
  "Xóm 3 - Thôn Lương Lễ": { type: "household", value: "Số 70" },
  "Xóm 2 - Thôn Lương Lễ": { type: "household", value: "Số 5" },
  "Xóm 1 - Thôn Lương Lễ": { type: "household", value: "Số 13" },
  "Đường Trần Nguyên Hãn": { type: "household", value: "Nguyễn Phong Phú" },
  "Đường Hồ Sỹ Thản": { type: "household", value: "Số 9" },
  "Đường Nguyễn Văn Linh": { type: "household", value: "Phan Văn Quynh (NVL)" },
  "Ngõ 01 - Hà Huy Tập": { type: "household", value: "Số 2" },
  "Đường Hà Huy Tập": { type: "household", value: "Số 28" },
  "Ngõ 01 - Bùi Thị Xuân": { type: "household", value: "Số 3" },
  "Đường Bùi Thị Xuân": { type: "household", value: "Số 6" },
  "Ngõ 02 - Đường Ngô Sỹ Liên": { type: "household", value: "Phùng Thạch Hàn Ngân" },
  "Ngõ 01 - Đường Ngô Sỹ Liên": { type: "household", value: "Nguyễn Thái Linh" },
  "Đường Ngô Sỹ Liên": { type: "household", value: "Số 22" },
  "Kiệt 35 - Đường Ngô Sỹ Liên": { type: "household", value: "Số 9" },
  "Đường Hai Bà Trưng": { type: "household", value: "Hoàng Thị Hằng (LD)" },
  "Đường Nguyễn Trãi": { type: "household", value: "Phan Anh Niêm" },
  "Đường Trần Hữu Dực": { type: "household", value: "Số 40" },
  "Đường Đặng Thai Mai": { type: "household", value: "Nguyễn Thị Hạnh" },
  "Đường Lê Hành": { type: "household", value: "Số 39" },
  "Đường Hùng Vương": { type: "household", value: "Số 12" },
  "Ngõ 22 - Hùng Vương": { type: "household", value: "Đoàn Quang Bào" },
  "Ngõ 30 - Hùng Vương": { type: "household", value: "Số 2" },
  "Đường Lê Duẩn": { type: "household", value: "Số 14" },
  "Ngõ 171 Lê Duẩn": { type: "household", value: "Số 2" }
};
